language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libxslt1-dev
      - libpcre3-dev
      - libssl-dev
      - libgeoip-dev
      - libgd-dev
  homebrew:
    packages:
      - geoip
      - gd
      - pcre
      - libxml2
    update: true

script:
  - mkdir build && cd build
  - if [ $TRAVIS_OS_NAME == linux ]; then cmake -DCMAKE_BUILD_TYPE=Release .. && make ; fi
  - if [ $TRAVIS_OS_NAME == osx ];   then cmake -DCMAKE_BUILD_TYPE=Release .. && make ; fi
