language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - if [ $TRAVIS_OS_NAME == linux ];   then cmake -DCMAKE_BUILD_TYPE=Release .. && make ; fi
  - if [ $TRAVIS_OS_NAME == osx ];     then cmake -DCMAKE_BUILD_TYPE=Release .. && make ; fi
  - if [ $TRAVIS_OS_NAME == windows ]; then cmake -G "Visual Studio 15 2017 Win64" .. ; fi
  - # TODO: MSBuild for windows
